### NumPy Tutorial
''' NumPy is a general purpose array-processing package. It provides a high-performance multidimentional
array object, and tools for working with these arrays it is the fundamental package for 
scientific computing with Python.'''

## What is an Array
''' An Array is a data structure that stores values of same data type. In Python, this is the main differrence
between arrays and lists. While Python lists can contain values corresponding to different data types, array in 
Python can only contain values corresponding to same data type.'''

In [2]:
import numpy as np

In [6]:
list = [1, 2, 3, 4, 5]

array = np.array(list)

In [7]:
type(array)

numpy.ndarray

In [8]:
array

array([1, 2, 3, 4, 5])

In [10]:
array.shape

(5,)

In [14]:
type(array)

numpy.ndarray

In [17]:
## MultiNested Array

my_list1 = [1, 2, 3, 4, 5]
my_list2 = [2, 3, 4, 5, 6]
my_list3 = [6, 7, 8, 9, 10]

array = np.array([my_list1, my_list2, my_list3])

In [18]:
array

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10]])

In [19]:
array.shape

(3, 5)

In [20]:
array.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 3,  4,  5],
       [ 6,  6,  7],
       [ 8,  9, 10]])